### ISSUE TITLE
Alt tags

### ISSUE THREAD

**Issue by conneralegre** [DRBJAX/f1-3-c2p1-colmar-academy#1]
Simplify - I recommend adding alt tags to your images. The purpose of alt attributes is to provide a text description of the contents of an image file - it also helps with accessibility.

Read more here: https://www.w3.org/wiki/HTML/Usage/TextAlternatives

Here is a more in-depth explanation on alt & accessibility if you are curious: https://webaim.org/techniques/alttext/

**Comment by DRBJAX** [comment]
I thought same thing after I reviewed my code. It's a habit I need to get into 100% of the time.
