### ISSUE TITLE
<source>

### ISSUE THREAD

**Issue by conneralegre** [DRBJAX/f1-3-c2p1-colmar-academy#4]
Simplify - Line 144 you have an opening `<source>` element, but `<source>` does not need a closing `</source>` element. For your video element to let a users browser know it does not support video, you can put the message below the `<source>` element like so:

```
<video controls>
	<source src="./resources/videos/thesis.mp4">
	Your browser does not support video
</video>
```

**Comment by DRBJAX** [comment]
Thanks.
