### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by conneralegre** [DRBJAX/f1-3-c2p1-colmar-academy#5]
Grade: **Meets Expectations**

Overall, this project is working great! It's completely responsive and works at all page sizes which is great for anyone viewing on a phone, laptop, or PC. A couple things I would change is to make sure you add alt tags to your images in order to provide our users with a text descriptor of the image in the event it does not load. The other would be to make sure to terminate your named character references (copyright) with a semicolon. Next steps, I would attempt to add some additional pages to the project which are also responsive and match the theme of Colmar Academy.

Nicely done!

**Comment by DRBJAX** [comment]
Thanks for your obviously diligent time in reviewing the code. It really helps to have an experienced developer catch all these little mistakes and to give feedback.
